### ISSUE TITLE
Any contribution guide? 

### ISSUE THREAD

**Issue by Torrencem** [wtklbm/rust-library-i18n#1]
The Readme says not to create PRs yet, but I was wondering if contributed translations were allowed? I'd be more than happy to volunteer some work on English - > French translation. Or if there were some guide for what kinds of contributions are allowed (or if no contributions will ever be allowed)

**Comment by wtklbm** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    I'm very sorry, my English is not good.Chinese:您好，非常感谢您的来信。目前 Rust 标准库翻译是通过 Cmtor 程序自动处理完成的，因为翻译 Rust 标准库是一项巨大的工作，并非是几个人就可以迅速完成，而且翻译的效率、时效性、质量也不能够保证，所以目前来说，还仅仅是通过 Cmtor 程序自动处理那些源代码文件。像您一样，我也非常愿意为 Rust 做出一些微薄的贡献，把翻译的工作做好。当前，我正在修改 Cmtor 程序来改善常见的错误，等修复了常见的错误以后，我可以制作一个比较好的版本，我认为在那个时候，才是我们去手动翻译那些源代码的最好时机。Google Translate:Hello, thank you very much for your letter. At present, the Rust standard library translation is automatically processed through the Cmtor program, because translating the Rust standard library is a huge task, which can not be completed quickly by a few people, and the efficiency, timeliness, and quality of translation cannot be guaranteed, so At present, it is only through the Cmtor program to automatically process those source code files. Like you, I am also very willing to make some meager contributions to Rust and do a good job of translation. Currently, I am modifying the Cmtor program to improve common errors. After the common errors are fixed, I can make a better version. I think that at that time is the best time for us to manually translate the source code.
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                wtklbm
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 5/14/2021 18:55，Matt ***@***.***> wrote： 



The Readme says not to create PRs yet, but I was wondering if contributed translations were allowed? I'd be more than happy to volunteer some work on English - > French translation. Or if there were some guide for what kinds of contributions are allowed (or if no contributions will ever be allowed)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Torrencem** [comment]
OK. Once you've finished that, if you make it easy to contribute, I'm sure that you will have a lot of volunteers willing you help you out. This is a good project.

好。一旦完成，如果你可以轻松地做出贡献，我相信你会有很多志愿者愿意帮助你。这是一个非常好的计划。(torrencem 朋友的翻译)
