### ISSUE TITLE
考虑通过GitHub Pages之类的方式提供在线预览版么？

### ISSUE THREAD

**Issue by Tarhyru** [wtklbm/rust-library-i18n#12]
如果想作为工具网站来查询，现在这个流程略微有些麻烦，我在思考，通过订阅这个仓库的更新，去更新一个存放Github Pages的仓库之类的是否合适，当然如果这里能提供预览感觉会方便很多。

**Comment by wtklbm** [comment]
我对这方面研究不多，如果您想到了好的点子，欢迎您的指点。

**Comment by Tarhyru** [comment]
我也谈不上有多懂，个人感觉理想情况下在 github workflows 里面，根据本仓库的提交去触发，在action里写构筑html的脚本，然后把静态资源，推到一个分支上，比如gh-pages，然后在仓库里设置就可以直接访问了。
设置文档：<https://docs.github.com/cn/pages/getting-started-with-github-pages/creating-a-github-pages-site>
或者简单一点，直接用产物创建个分支配置预览，后续不更新也是个办法。

**Comment by wtklbm** [comment]
目前比较棘手的问题是构建 HTML 文档的脚本总是会出现各种报错，之前构建的时候一个错误也没有，等过一段时间，等发新版的时候再次构建就报错了。如果以后找到了稳定的构建 HTML 脚本的话，能够把 HTML 又快又好的构建出来，可以考虑 workflows，随着 Rust 的更新实时更新 HTML 文档。
如果构建的脚本不稳定，只能通过手动构建，就显得太麻烦了。
