### ISSUE TITLE
错误提示 和 rust编译器报错 汉化在哪里修改？

### ISSUE THREAD

**Issue by zhifu3158** [wtklbm/rust-library-i18n#17]
@wtklbm  请问vs code 错误提示（语句错误。或变量错误等）如何汉化？或者从什么地方进行汉化修改呢？？如果rust编译器报错也能汉化 那就太太太太好啦~~~

**Comment by wtklbm** [comment]
语句错误。或变量错误等错误字符串都是在代码里写死的。如果汉化它们，就需要汉化者一个一个去鉴别代码中的哪些字符串需要被汉化，哪些字符串不需要，当汉化好后，还需要重新编译 Rust。所以，通过像汉化文档这样的方式来汉化错误字符串并不理想。

**Comment by tch1121** [comment]
@zhifu3158 错误提示应该是由LSP提供的，可以要求扩展支持i18n
