### ISSUE TITLE
提供更便捷的安装方式

### ISSUE THREAD

**Issue by wtry** [wtklbm/rust-library-i18n#22]
目前的安装方式，依赖太多，而且采用了替换原有文件的方式，不太便捷
文档和rust版本强关联，但是很多时候，不同系统平台更新速度不一样，造成还没有更新到最新版本的系统，无法使用

目前主流的两个编辑器，都可以提供插件

例如 https://github.com/fw6669998/php-doc
phpstorm的中文手册插件，有对应文档的时候，会显示 中文，没有对应文档的时候，显示官方的英文手册

希望可以提供一个 idea的 rust中文文档插件

**Comment by wtklbm** [comment]
是的，插件是一种实现文档翻译的有效方法，它不仅仅局限于 Rust，甚至是 TS 或 Python 等等。很抱歉，目前我没有太多时间来编写它。如果您愿意，可以尝试编写呢。
