### ISSUE TITLE
能否在仓库里保留老版本的翻译文件

### ISSUE THREAD

**Issue by xun-mi-git** [wtklbm/rust-library-i18n#23]
# 希望能提供老版本的翻译文件
平台架构: loongarch64
rustc版本: rustc 1.58.1
原因: 受平台影响,我无法使用rustup, 因为rust官方未支持我们架构, 导致我使用的版本并非官方最新版
希望作者可以添加历史版本,要是因为历史版本使用人数较少作者可以在git时候能保存历史版本或则提供不同版本的标签.

**Comment by wtklbm** [comment]
我制作了一个 v1.58.1 版本的文档，您可以到这里下载 <https://github.com/wtklbm/rust-library-i18n/releases/tag/v1.58.1> zip 文件，自行解压安装

**Comment by xun-mi-git** [comment]
十分感谢
