### ISSUE TITLE
linux 下  + vscode 怎么设置中文提示

### ISSUE THREAD

**Issue by bernadit** [wtklbm/rust-library-i18n#3]
我是 llinux mint 20, 用的是 vscode, 默认 cargo 位置 于 ~/.cargo

**Comment by wtklbm** [comment]
您好，我刚刚更新了一下文档，您可以按照文档重新操作一遍呢，另外需要注意的是，您需要使用 `stable` 版本才能得到智能提示，`nightly` 版本是不受支持的。

**Comment by bernadit** [comment]
谢谢，非常感谢

**Comment by bernadit** [comment]
![image](https://user-images.githubusercontent.com/59190957/118499991-ff695e80-b759-11eb-8a7d-268312608f8d.png)

搞定了，谢谢
