### ISSUE TITLE
能否将 rust-library-i18n 用发行版的方式配置

### ISSUE THREAD

**Issue by taotieren** [wtklbm/rust-library-i18n#9]
能否将 rust-library-i18n 用发行版的方式配置？
如果这样的话 Linux 用户可以将其打包到 Linux 仓库，可以做到安装软件包就能替换成中文版本，而且也不影响使用，或者通过 Actions 自动编译成一些主流 Linux 的软件包，用户自己下载就能安装。

**Comment by taotieren** [comment]
我这边能将其打包成 AUR 包，可以参考一下

**Comment by wtklbm** [comment]
感谢您的建议。因为目前我有别的事在做，以后再来实现它吧。

**Comment by taotieren** [comment]
或者给官方提建议加入这个功能？这样可以通过安装语言包来支持不同语言的配置方式

**Comment by taotieren** [comment]
如果能将官方的 `rust-src` 同步打包一份，替换其中的 `library` ，便将其打包成 `rust-src-zh-CN`

**Comment by wtklbm** [comment]
"官方 rust-src 同步打包" 这个不太好实现，因为它的包的源代码并不是直接对我们可见的，我们可以通过 `rustup component` 安装，却无法知道这个组件包的从哪里下载的，假设真的打包了 `rust-src-zh-CN` 组件，我们也无法解决自定义组件如何安装的问题。

以后有时间的话，可以写个叫做 rustcn 的程序，通过该程序完成自动更新卸载替换操作。也可以写两个 shell 脚本，一个用于  Windows，一个用于 macOS 和 Linux。用户可以通过 `curl https://xxx` 的方式下载和使用最新的中文翻译。

**Comment by taotieren** [comment]
我看 Arch Linux 的 [rust](https://github.com/archlinux/svntogit-packages/blob/packages/rust/trunk/PKGBUILD) 的  PKGBUILD 中有说明：
```bash
package_rust-src() {
  pkgdesc="Source code for the Rust standard library"
  depends=(rust)

  cp -a dest-src/* "$pkgdir"

  mkdir -p "$pkgdir/usr/share/licenses"
  ln -s rust "$pkgdir/usr/share/licenses/$pkgname"
}
```

**Comment by wtklbm** [comment]
嗯嗯，这个可以在继续研究下。

**Comment by baronjason033** [comment]
第三步
构建 HTML 离线静态文档 
python x.py doc library/std 是怎么操作来着？能详细点吗？小白看不懂

**Comment by wtklbm** [comment]
> 第三步 构建 HTML 离线静态文档 python x.py doc library/std 是怎么操作来着？能详细点吗？小白看不懂

之前已经回复过您了，您可以下载我之前备份过的  1.57.0 版本的已经构建好的文档：https://wwt.lanzouo.com/i189ux7bo3i 如果您只想通过源码构建的话，您可以跳转到 Rust 官方仓库，了解 Rust 构建流程，探索更好的构建 HTML 文档的操作。该项目所提供的构建命令仅供参考，如果您有更好的构建方式，欢迎您的 PR。谢谢。

**Comment by wtklbm** [comment]
目前 Windows 平台的安装脚本初步更新，[安装文档](https://github.com/wtklbm/rust-library-i18n/blob/main/Install.md) 也更新了。

**Comment by wtklbm** [comment]
macOS 和 Linux 平台的安装脚本也完成了。
